# Generated by Django 4.2.1 on 2023-05-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtags', models.CharField(max_length=2000, verbose_name='해시태그')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('comments', models.IntegerField(default=0, verbose_name='댓글수')),
                ('slide', models.BooleanField(default=False, verbose_name='슬라이드여부')),
                ('url', models.CharField(max_length=2000, verbose_name='주소')),
                ('created_at', models.DateTimeField(verbose_name='작성일시')),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='단어')),
                ('frequency', models.IntegerField(default=0, verbose_name='빈도수')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore_tab_crawling.content', verbose_name='콘텐츠')),
            ],
            options={
                'db_table': 'hashtag',
            },
        ),
        migrations.AddConstraint(
            model_name='hashtag',
            constraint=models.UniqueConstraint(fields=('content_id', 'text'), name='unique_content_text'),
        ),
    ]
